server:
  port: 3333
eureka:
  instance:
    hostname: localhost
  client:
   registerWithEureka: true
   fetchRegistry: true
   serviceUrl:
    defaultZone: http://127.0.0.1:1111/eureka/
    healthcheck:
      enabled: true
    
spring:    
  application:
    name: school-service